update curl in cd

diff --git a/.github/workflows/ci-deploy.yml b/.github/workflows/ci-deploy.yml
--- a/.github/workflows/ci-deploy.yml
+++ b/.github/workflows/ci-deploy.yml
@@ -258,13 +258,6 @@ jobs:
           username: root
           key: ${{ secrets.SSH_KEY }}
           script: |
-            for i in {1..3}; do
-              if curl -sf http://localhost:${{ vars.WEB_PORT }}/api/health >/dev/null; then
-                echo "Health check passed"
-                exit 0
-              fi
-              echo "Waiting for server..."
-              sleep 3
-            done
-            echo "Health check failed"
-            exit 1
+            curl --retry 3 --retry-delay 3 --max-time 5 -f -sS http://localhost:${{ vars.WEB_PORT }}/api/health >/dev/null \
+              && echo "Health check passed" \
+              || (echo "Health check failed" && exit 1)
